/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package tools.vitruv.extensions.delta.dsl.ide


/**
 * Use this class to register ide components.
 */
class DeltaModulIdeModule extends AbstractDeltaModulIdeModule {
}
