/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package tools.vitruv.extensions.delta.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DeltaModulUiModule extends AbstractDeltaModulUiModule {
}
