/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package tools.vitruv.extensions.delta.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DeltaModulRuntimeModule extends AbstractDeltaModulRuntimeModule {
}
