/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package tools.vitruv.extensions.delta.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DeltaModulStandaloneSetup extends DeltaModulStandaloneSetupGenerated {

	def static void doSetup() {
		new DeltaModulStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
